/**
 * Explanation service.
 * Produces a simple "AI-like" explanation object based on scoring signals.
 */

function summarizeSignals(signals) {
  if (!signals?.length) return 'No elevated risk signals were detected.';
  const top = [...signals].sort((a, b) => (b.points || 0) - (a.points || 0)).slice(0, 3);
  return top.map((s) => s.message).join(' ');
}

class ExplanationService {
  // PUBLIC_INTERFACE
  buildExplanation(claim, scoreResult) {
    /**
     * Build an explanation for a claim.
     *
     * @param {object} claim
     * @param {{fraud_score:number, fraud_signals:Array<object>}} scoreResult
     * @returns {object} explanation payload
     */
    const score = scoreResult?.fraud_score ?? claim?.fraud_score ?? claim?.riskScore ?? 0;
    const signals = scoreResult?.fraud_signals ?? claim?.fraud_signals ?? [];

    const riskLevel = score >= 85 ? 'HIGH' : score >= 70 ? 'MEDIUM' : 'LOW';

    return {
      generatedAt: new Date().toISOString(),
      riskLevel,
      score,
      summary: summarizeSignals(signals),
      topSignals: (signals || []).slice(0, 5),
      recommendedActions:
        riskLevel === 'HIGH'
          ? ['Escalate to SIU', 'Validate documentation', 'Contact claimant for clarification']
          : riskLevel === 'MEDIUM'
            ? ['Route to investigator queue', 'Request additional supporting docs']
            : ['Proceed with standard review'],
      disclaimer:
        'This explanation is generated by a deterministic rules engine (demo). It should not be used as the sole basis for adverse decisions.',
    };
  }
}

module.exports = new ExplanationService();
